---
- name: Enable services
  service:
    name: "{{ item }}"
    enabled: True
  loop:
    - zabbix-server
    - zabbix-agent
    - nginx

- name: Start services
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - zabbix-server
    - zabbix-agent
    - nginx

- name: Enable PHP for PostgreSQL
  service:
    name: "php{{ zabbix_php_version }}-fpm"
    enabled: True
  when: zabbix_database == 'pgsql'

- name: Start PHP for PostgreSQL
  service:
    name: "php{{ zabbix_php_version }}-fpm"
    state: restarted
  when: zabbix_database == 'pgsql'
